image: atlassian/default-image:5

pipelines:
  default:
    - step:
        script:
          - apt update && apt install -y flex bison docutils-common
          - autoreconf -i
          - ./configure
          - make distcheck
